### ISSUE TITLE
(Re-)Add human-readable names to description?

### ISSUE THREAD

**Issue by resuscv** [TobiasTheViking/flickrannex#10]
I noticed in 4c55a34cd5e the TODO to "use the filename instead of git-annex filename" was removed from the CHANGELOG.md

...and in 02bc9cfff "The real name of the picture will be in the description" was removed from README.md

Is there any way to link the images uploaded to any (or all) the human-readable file names?

Or, another way to ask the question, what was the difficulty?

**Comment by resuscv** [comment]
OK, I started digging into the code - the file name should be in the description...

So...refreshing flickr a few times and voila!  File name in the description.

Sorry for the noise.   _facepalm_

**Comment by TobiasTheViking** [comment]
It should be noted that this only works for direct mode repositories. Indirect mode won't work as you want.

This is a limitation of git-annex, and not of the hook.
