### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by tex** [TobiasTheViking/flickrannex#5]
Currently credential are stored in the flickrannex pwd. This prevents to use the flickannex with different gitannex-ed directories.
AFAIK the credentials should be stored in .git/annex/creds.

**Comment by TobiasTheViking** [comment]
Hopefully that file will entirely disappear. I expect a future update of git-annex will allow all settings to be handled either through git-annex commands, and/or in the webassistance.

So, for now this is a "WONTFIX", but this will be looked at soonish i hope.

**Comment by TobiasTheViking** [comment]
Added --configfile in 0.1.9
