### ISSUE TITLE
Make proper installation possible

### ISSUE THREAD

**Issue by magthe** [TobiasTheViking/flickrannex#7]
The current "installation procedure" is a bit irritating.

I'd love to see a `setup.py` added.  Is there anything in the design preventing a central installation? (Besides the configuration file that's created initially, but that could easily be moved into `~/.config` I think.)

If the config file is all preventing it I'd be happy to put together a couple of patches.  This way the hook could be packaged up in Linux distros ;)

**Comment by TobiasTheViking** [comment]
Hm, my thought was more that it should be setup entirely by git-annex. And all configuration managed by git-annex.

I guess that is still doable, but i'm not sure of the right method to implement this. Does the hook even make sense as a standalone package in linux distros.

**Comment by magthe** [comment]
I think it does, as it isn't distributed with git-annex itself.

I was thinking a standard `setup.py` using `distutils` and then modify it so that the configuration is read from the user's $HOME instead.  Even if the configuration moves into each individual annex it still makes sense to install it centrally on multi-user systems (and packaging it eases use on single-user systems too).

**Comment by TobiasTheViking** [comment]
I must admit i have played with neither of those. If you make a PR i'll merge it.

And then see what you did and do it in the other ones :)

**Comment by magthe** [comment]
I've put a few changes into the `devo` branch in my fork.  Would you please have a look at them and let me know what you think?

I couldn't help but do a bit of clean-up as well, I hope you don't mind.

**Comment by TobiasTheViking** [comment]
Looks good, but i have a few issues:

1) The "credits" for other patches shouldn't be removed entirely.
2) https://github.com/magthe/flickrannex/commit/e49038bffc5220e82f631ec6062497eb67c664f1 <- this one i can not accept. The two variables are pushed like that to allow for IOC in my testing framework. (Granted, i haven't made unit/integration tests for this.... yet)

Fix these two, and pop me a PR, i'll merge it :)

**Comment by magthe** [comment]
1. I've re-added the credit for the tEXt patch to png.
2. With the change it's still IoC (inversion of control or dependency injection), at least according to the definition found in Wikipedia:
   
   > For example, class A may delegate behavior to interface I which is implemented by class B; the assembler instantiates A and B then injects B to A.
   
   Here `flickrannex.py` is the "assembler", the module members `CommonFunctions.dbglevel` and CommonFunctions.plugin`is the "interface I",`CommonFunctions`is "A" and the values in`dbglevel`and`plugin`in`flickrannex.py` is "B".
   
   I also think it's arguable if the original code actually _is_ IoC since there is no "assembler" involved; in the original code "A" itself pulls in "B".
   
   Another issue with using the original code, where `CommonFunctions` itself pulls in the values from the `main` module is that when using `distutils` the `main` module won't be the `flickrannex` script, but rather a "wrapper script" which loads and runs the real script.  This causes the reflection to fail.  I'm not sure that's well described, but if you run `easy_install --user .` and inspect `~/.local/bin/flickrannex` and `~/.local/lib/python2.7/site-packages/flickrannex-0.0-py2.7.egg` I'm sure you'll see what I mean.

**Comment by nrbray** [comment]
Just a quick note: it was not clear to me that the installation command should be perhaps

```
easy_install .
```

which then seemed to work for me.
From there I am left wondering
1) where will the flickrannex.config file belong
2) how do I uninstall
3) if . is in my path and flickrannex is now installed in /usr/local/bin will there be a difference in behaviour if I execute flickrannex from .

**Comment by magthe** [comment]
I added an example for `easy_install` to `README.md`.

Answers:
1. The config file lives in a per-user location, the code uses `appdirs` to locate it.  This means that on Unix systems it'll live in `~/.config/flickrannex/`.
2. Uninstalling is a shortcoming of `easy_install`, there is however an alternative called [`pip`](http://pypi.python.org/pypi/pip/) which can perform uninstalls (see [this on SO](http://stackoverflow.com/questions/1231688/how-do-i-remove-packages-installed-with-pythons-easy-install)).
3. Nope, you run the `flickrannex` you'd expect, i.e. the first one found according to `$PATH`.  However, if you play around with changes to the underlying libs then you need to make sure that python finds your changed library first.

**Comment by TobiasTheViking** [comment]
If i make unittests/integrationtests later i can just push those values too.

It will different from the "master" of that file. But the CommonFunctions included in flickrannex is extremely stripped anyways. So really makes no sense to hold on to that legacy. You implement it however seems best for you.

I just pushed a new version to trunk, some minor changes but probably best to keep your branch in sync.

**Comment by TobiasTheViking** [comment]
Any progress magthe?

**Comment by TobiasTheViking** [comment]
I've pushed a version 0.1.9 that has a --configfile option.

It should be trivial to also check ~/.config/flickrannex/ for a config file, in the case that no file is provided in commandline.

There also was some refactor, but not sure if it touches anything you have changed.
